### ISSUE TITLE
デスクトップ通知用のメッセージの翻訳が存在しない言語に設定している場合、デスクトップ通知を受け取る設定にした種別の通知がリアルタイムで確認できない

### ISSUE THREAD

**Issue by kmycode** [kmycode/mastodon#815]
### バグの再現手順

1. 通知のグループ化を有効にする
2. 通知画面を開いたままの状態にする
3. 誰かから投稿に返信してもらう

### 期待する動作

通知画面に返信が表示される

### 実際の動作

表示されない
通知画面を更新すると表示はされる

### 詳しい情報

ストリーミング処理の何処かでミスがあったかも

### バグが発生したkmyblueサーバーのドメイン

kmy.blue

### バグが発生したkmyblueのバージョン

14.0-dev

**Comment by kmycode** [comment]
引用では発生せず

**Comment by kmycode** [comment]
エラー

```
core.js:143 Uncaught TypeError: A message must be provided as a String or AST.
    at new e (core.js:143:19)
    at notifications.js:164:21
    at redux-thunk.legacy-esm.js:5:14
    at dispatch (redux.legacy-esm.js:371:38)
    at Object.onReceive (streaming.js:106:11)
    at stream.js:118:20
    at Array.forEach (<anonymous>)
    at received (stream.js:117:8)
    at stream.js:250:25
    at e.value (index.js:14:128)
```

追記：これ、デスクトップ通知のエラーです。今回の件とは無関係っぽい

追記：と思ったけど、このエラーのせいで処理が止まってしまったのが直接の原因っぽい

**Comment by kmycode** [comment]
mastodon.socialでは再現せず
開発環境（`kb_development`ブランチ）では再現せず

（※いずれもデスクトップ通知は無効にした状態で動作確認）

**Comment by kmycode** [comment]
現在、Mastodon本家は開発中で、一部メッセージの翻訳が未完
日本語翻訳のない通知を受け取った時に、それのデスクトップ通知用メッセージを作る処理でエラーが出ている
再現条件が複雑だが、mastodon.socialでも再現しましたので本家由来のバグと推定できます
